# Generated by Django 4.2.18 on 2025-01-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task',
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
