# Generated by Django 4.2.18 on 2025-01-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0002_remove_todo_task_todo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
    ]
