"""Initial migration

Revision ID: cf6d9dbf96bc
Revises: 
Create Date: 2025-01-23 14:30:22.451710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6d9dbf96bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('years', sa.String(length=20), nullable=True),
    sa.Column('degree', sa.String(length=40), nullable=True),
    sa.Column('university', sa.String(), nullable=True),
    sa.Column('address', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('years', sa.String(length=20), nullable=True),
    sa.Column('post', sa.String(length=40), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('address', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=20), nullable=True),
    sa.Column('knowledge', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    op.drop_table('experience')
    op.drop_table('education')
    # ### end Alembic commands ###
